import java.io.*;
import java.util.*;

public class AllJavaFilesCollector {
    public static void main(String[] args) {
        String srcDir = "/home/muratsivas76/istasyon/java/raja_extended/src";
        String outFile = "/home/muratsivas76/istasyon/java/raja_extended/tool/files_all.txt";
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outFile))) {
            writer.write("// Collected Java Source Files\n");
            writer.write("// Generated by AllJavaFilesCollector\n\n");
            
            processJavaFiles(new File(srcDir), writer, srcDir);
            System.out.println("All Java files collected successfully to tool/files_all.txt!");
        } catch (IOException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    private static void processJavaFiles(File dir, BufferedWriter writer, String basePath) throws IOException {
        File[] files = dir.listFiles();
        if (files == null) return;

        for (File file : files) {
            if (file.isDirectory()) {
                processJavaFiles(file, writer, basePath);
            } else if (file.getName().endsWith(".java")) {
                writeFileContent(file, writer, basePath);
				System.out.println ("Added: "+(file.getAbsolutePath ())+"");
            }
        }
    }

    private static void writeFileContent(File javaFile, BufferedWriter writer, String basePath) throws IOException {
        String relativePath = javaFile.getParent().substring(basePath.length());
        
        writer.write("// =========================================\n");
        writer.write("// File: " + relativePath + File.separator + javaFile.getName() + "\n");
        writer.write("// =========================================\n\n");
        
        try (BufferedReader reader = new BufferedReader(new FileReader(javaFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                writer.write(line);
                writer.newLine();
            }
        }
        
        writer.write("\n\n");
    }
	
}
